### Python für Kids - Kapitel 5 ###
# Autor: Gregor Lingl
# Datum: 7. 8. 2009
# politiker.py
# Vorlage zur Erarbeitung von Aufgabe 2: 

# !!! ACHTUNG: DIES IST NOCH KEIN PYTHON-PROGRAMM
# !!! WIE DARAUS DAS FERTIGE politiker.py GEMACHT
# !!! WIRD ERFÄHRST DU AUS DER BEILIEGENDEN DATEI
#
# politiker.txt
#
# !!! BITTE DURCHLESEN UND DURCHARBEITEN


DER UNBEDINGTE WILLE
DAS ERKLÄRTE ZIEL
DIE SELBSTVERSTÄNDLICHE PFLICHT
DIE GESCHICHTLICHE AUFGABE
DIE UNERWARTETE GNADE
DIE TIEFE EINSICHT
DIE EINFACHE ABSICHT
DIE SCHLICHTE NOTWENDIGKEIT
DIE EINDEUTIGE ERKENNTNIS
DIE HOHE AMTSPFLICHT

HIER UND JETZT
IN ALLER OFFENHEIT
IN GEMEINSAMER ANSTRENGUNG
ZWISCHEN GESTERN UND MORGEN
OHNE "WENN" UND "ABER"
NOTFALLS IM ALLEINGANG
GEGEN ALLE WIDERSTÄNDE
GANZ UNMISSVERSTÄNDLICH
IN GUT UND BÖSE
AUCH GEGEN DEN ZEITGEIST

MITEINANDER ZU REDEN
KRAFTVOLL ANZUPACKEN
NACH VORNE ZU BLICKEN
DIE KONTINUITÄT ZU WAHREN
GANZ BEWUSST ÖSTERREICHISCH ZU SEIN
DAS ZIEL ANZUSTREBEN
LETZTLICH ALLEIN ZU SEIN
DAS ICH VOR DAS WIR ZU STELLEN
DEM VATERLAND ZU DIENEN
GANZ EINFACH OBEN ZU BLEIBEN

